### ISSUE TITLE
Checklist para o curso 1

### ISSUE THREAD

**Issue by sahrosa** [design-na-escola/projeto#41]
**Antes:**
- [ ] Preparar o lanche
- [ ] Levar o lanche para o local
- [ ] Comprar materiais
- [ ] Dar um oi pro xx do Museu de Comunicação
- [ ] Imprimir a estrutura do curso 
- [ ] Pegar papelão no super
- [ ] Confirmar Beta/Anna como observador

**Durante:**
- [ ] Aplicar o formulário inicial
- [ ] Registrar o curso
- [ ] Aplicar o formulário final
- [ ] Mini retrospectiva sobre o curso

**Depois:**
- [ ] Limpeza do local
- [ ] Anotar o aprendizado do que melhorar
- [ ] Preparar post sobre como foi o curso
